--Shop
SELECT sho.NAME as NAME, sta.NAME as TOWN, reg.NAME as REGION, lan.NAME as COUNTRY
FROM DB2INST1.SHOPID sho 
join DB2INST1.STADTID sta on sho.STADTID = sta.STADTID
join DB2INST1.REGIONID reg on sta.REGIONID = reg.REGIONID
join DB2INST1.LANDID lan on reg.LANDID = lan.LANDID

--Artikel
SELECT art.NAME as NAME, gru.NAME as PRODUCTGROUP, fam.NAME as PRODUCTFAMILY, kat.NAME as PRODUCTCATEGORY
FROM DB2INST1.ARTICLEID art 
join DB2INST1.PRODUCTGROUPID gru on art.PRODUCTGROUPID = gru.PRODUCTGROUPID
join DB2INST1.PRODUCTFAMILYID fam on gru.PRODUCTFAMILYID = fam.PRODUCTFAMILYID
join DB2INST1.PRODUCTCATEGORYID kat on kat.PRODUCTCATEGORYID = fam.PRODUCTCATEGORYID