CREATE TABLE "VSISP17"."DIMARTICLE"
(
   ARTICLEID int PRIMARY KEY NOT NULL,
   NAME varchar(50),
   PRODUCTGROUP varchar(50),
   PRODUCTFAMILY varchar(50),
   PRODUCTCATEGORY varchar(50)
)
;
CREATE TABLE "VSISP17"."DIMDAY"
(
   DAYID int PRIMARY KEY NOT NULL,
   DATE varchar(50),
   MONTH varchar(50),
   QUARTER varchar(50),
   YEAR varchar(50)
)
;
CREATE TABLE "VSISP17"."DIMSHOP"
(
   SHOPID int PRIMARY KEY NOT NULL,
   NAME varchar(50),
   TOWN varchar(50),
   REGION varchar(50),
   COUNTRY varchar(50)
)
;
CREATE TABLE "VSISP17"."FACT"
(
   DAYID int NOT NULL,
   SHOPID int NOT NULL,
   ARTICLEID int NOT NULL,
   SOLD int,
   TURNOVER int,
   CONSTRAINT SQL130620144830530 PRIMARY KEY (DAYID,SHOPID,ARTICLEID)
)
;
CREATE UNIQUE INDEX SQL130620144430550 ON "VSISP17"."DIMARTICLE"(ARTICLEID)
;
CREATE UNIQUE INDEX SQL130620144008560 ON "VSISP17"."DIMDAY"(DAYID)
;
CREATE UNIQUE INDEX SQL130620144148880 ON "VSISP17"."DIMSHOP"(SHOPID)
;
ALTER TABLE "VSISP17"."FACT"
ADD CONSTRAINT FOREIGNKEYSHOP
FOREIGN KEY (SHOPID)
REFERENCES "VSISP17"."DIMSHOP"(SHOPID)
;
ALTER TABLE "VSISP17"."FACT"
ADD CONSTRAINT FOREIGNKEY
FOREIGN KEY (DAYID)
REFERENCES "VSISP17"."DIMDAY"(DAYID)
;
ALTER TABLE "VSISP17"."FACT"
ADD CONSTRAINT FOREIGNKEYARTICLE
FOREIGN KEY (ARTICLEID)
REFERENCES "VSISP17"."DIMARTICLE"(ARTICLEID)
;
CREATE UNIQUE INDEX SQL130620144830170 ON "VSISP17"."FACT"
(
  DAYID,
  SHOPID,
  ARTICLEID
)
;
